/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompetenceDto } from '../../models/competence-dto';

export interface ApiCompetenceCompetencesPost$Params {
      body?: CompetenceDto
}

export function apiCompetenceCompetencesPost(http: HttpClient, rootUrl: string, params?: ApiCompetenceCompetencesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CompetenceDto>> {
  const rb = new RequestBuilder(rootUrl, apiCompetenceCompetencesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompetenceDto>;
    })
  );
}

apiCompetenceCompetencesPost.PATH = '/api/Competence/competences';
