/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginModel } from '../../models/login-model';
import { UserDto } from '../../models';
import { UserResponse } from '../../models/UserResponse';

export interface ApiAuthLoginPost$Params {
      body?: LoginModel
}

export function apiAuthLoginPost(http: HttpClient, rootUrl: string, params?: ApiAuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token'?: string;
'user'?:UserResponse;
}>> {
  const rb = new RequestBuilder(rootUrl, apiAuthLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }


  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'token'?: string;
      'user'?:UserResponse
      }>;
    })
  );
  
}

apiAuthLoginPost.PATH = '/api/Auth/login';
