/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
export interface CandidatDto {
  Status: string;
  Competences?: Array<Competence> | null;
  Cv?: string | null;
  Email?: string | null;
  Firstname?: string | null;
  Id?: string;
  Lastname?: string | null;
  Telephone?: string | null;
  AppliedDate?: string | null;
}
