/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
import { CandidatDto } from './candidat-dto';
export interface JobOffer {

  Id?: number;
  Competences?: Array<Competence> | null;
  Description?: string | null;
  Experience?: number;
  Location?: string | null;
  candidates: CandidatDto[];
  Salary?: number;
  Title?: string | null;
  filteredCandidates?: CandidatDto[];
}
