/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
export interface JobOfferDtoCreate {
  Competences?: Array<Competence> | null;
  Description?: string | null;
  Experience?: number;
  Location?: string | null;
  Salary?: number;
  Title?: string | null;
}
