/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string | null;
  firstname?: string | null;
  id?: string;
  lastname?: string | null;
  telephone?: string | null;
}
