/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmployeDto } from '../../models/employe-dto';

export interface ApiEmployeManagementGet$Params {
}

export function apiEmployeManagementGet(http: HttpClient, rootUrl: string, params?: ApiEmployeManagementGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeDto>>> {
  const rb = new RequestBuilder(rootUrl, apiEmployeManagementGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EmployeDto>>;
    })
  );
}

apiEmployeManagementGet.PATH = '/api/EmployeManagement';
