/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ApplicationService } from './services/application.service';
import { AuthService } from './services/auth.service';
import { CandidatManagementService } from './services/candidat-management.service';
import { CompetenceService } from './services/competence.service';
import { EmployeeService } from './services/employe-management.service';
import { JobOfferService } from './services/job-offer.service';
import { UserManagementService } from './services/user-management.service';
import { SurveyService } from './services/survey.service'; // Import du SurveyService


/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ApplicationService,
    AuthService,
    CandidatManagementService,
    CompetenceService,
    EmployeeService,
    JobOfferService,
    UserManagementService,
    ApiConfiguration,
    SurveyService, // Ajout du SurveyService
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
