/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobOfferDtoCreate } from '../../models/job-offer-dto-create';

export interface ApiJobOfferCreatePost$Params {
      body?: JobOfferDtoCreate
}

export function apiJobOfferCreatePost(http: HttpClient, rootUrl: string, params?: ApiJobOfferCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<JobOfferDtoCreate>> {
  const rb = new RequestBuilder(rootUrl, apiJobOfferCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
    console.log('Request payload:', params.body);
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);
  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobOfferDtoCreate>;
    })
  );
}

apiJobOfferCreatePost.PATH = '/api/JobOffer/create';
