/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobOfferDtoCreate } from '../../models/job-offer-dto-create';
import { JobOffer } from '../../models/job-offer';

export interface ApiJobOfferGet$Params {
}

export function apiJobOfferGet(http: HttpClient, rootUrl: string, params?: ApiJobOfferGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<JobOffer>>> {
  const rb = new RequestBuilder(rootUrl, apiJobOfferGet.PATH, 'get');
  if (params) {
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);
  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<JobOffer>>;
    })
  );
}

apiJobOfferGet.PATH = '/api/JobOffer';
